config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "home#index"
  resources :blogs do
    resources :posts
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "signup", to: "registrations#new"
  post "signup", to: "registrations#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :blog, optional: true
  has_many :post_tags
  has_many :comments
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  has_one :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post_tag
end

app/models/user.rb
class User < ApplicationRecord
  has_one :blog
  has_many :comments
  has_secure_password
  validates :email, presence: true, format: {with: /\A[^@\s]+@[^@\s]+\z/, message: "nieprawidłowy adres e-mail" }
  validates :login, presence: true
  validates :nickname, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :find_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to @blog, notice: 'The blog was created!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Update successful'
    else
      render ‘edit’
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: 'blog destroyed'
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :user_id)
  end
  def find_blog
    @blog = Blog.find(params[:id])
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # before_action :find_blog

  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.where(blog_ID: @blog.id)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'The post was created!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Update successful'
    else
      render ‘edit’
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'blog destroyed'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :public)
  end

  def find_post
    @post = @blog.posts.find(params[:id])
  end

  # def find_blog
  #   @blog = Blog.find(params[:id])
  # end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "Rejestracja zakończona sukcesem"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :login, :nickname, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title, placeholder: 'Type the post title here' %><br>
  <%= f.label :user_id %><br>
  <%= f.number_field :user_id, placeholder: 'Type the user_id here' %><br>

  <%= f.submit %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit blog</h1>
<%= render 'form' %>
<%= link_to 'Back', blog_path %>

app/views/blogs/index.html.erb
<!--<div class="underlay"></div>-->
<!--<div class="description">-->
<!--  <h1>Witaj na stronie Blogi!</h1>-->
<!--  <p>w trakcie pracy.</p>-->
<!--</div>-->
<h1><%= link_to "New Blog", new_blog_path(@blog) %></h1>

<% @blogs.each do |blog| %>
  <h3><%= link_to blog.title, blog %></h3>


<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>
<%= render 'form' %>
<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>
<%= link_to "Edit", edit_blog_path(@blog) %>
<%= link_to "Delete", @blog, method: :delete, data: { confirm: "Are you sure?" }%>
<%= link_to 'Back', blogs_path %>
<%= link_to 'posty', blog_posts_path(@blog)%>

<%# @posts.each do |post| %>
<!--  <h3><%#= post.title%></h3>-->
<%# end %>

app/views/home/index.html.erb
<p class='content p-2'>Find me in app/views/home/index.html.erb</p>
<div class="underlay"></div>
<div class="description">
  <h1>Witaj na stronie głównej!</h1>
  <p>w trakcie pracy.</p>
  <%= link_to 'przejdź do blogów', blogs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogProjekt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="columns" >
    <div id="menu" >
      <nav class="navbar navbar-expand-md">
        <a class="navbar-brand" href="http://127.0.0.1:3000/">Blog</a>
        <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#main-navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="main-navigation">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#">Log in</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Register</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <div id="content" >
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title, placeholder: 'Type the post title here' %><br>
  <%= f.label :user_id %><br>
  <%= f.number_field :user_id, placeholder: 'Type the user_id here' %><br>

  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= render 'form' %>
<%= link_to 'Back', post_path %>

app/views/posts/index.html.erb
<!--<h1><%#= link_to "New Post", new_post_path(@post) %></h1>-->


<%# @posts.each   do |post| %>
<!--  <h2><%#=  post.title %></h2>-->
<!--  <h0><%#=  post.content %></h0>-->

<%# end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= link_to "Edit", edit_blog_path(@post) %>
<%= link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" }%>
<%= link_to 'Back', posts_path %>